version: '3.5'

services:
  postgres:
    container_name: rockelivery_database
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
    postgres: